apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecommerce-playwright
  namespace: playwright
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ecommerce-playwright
            image: dresseljo/ecommerce-playwrightservice:latest
          restartPolicy: OnFailure